#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/GreenAPP.jar:$APPDIR/lib/core.jar:$APPDIR/lib/eeml.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/SpringGUI.jar" GreenAPP
